"""
This type stub file was generated by pyright.
"""

"""filter"""

class FilterStack:
    def __init__(self, strip_semicolon=...) -> None: ...
    def enable_grouping(self):  # -> None:
        ...
    def run(self, sql, encoding=...):  # -> Generator[Statement | Any, Any, None]:
        ...
