"""
This type stub file was generated by pyright.
"""

class StatementSplitter:
    """Filter that split stream at individual statements"""
    def __init__(self) -> None: ...
    def process(self, stream):  # -> Generator[Statement, Any, None]:
        """Process the stream"""
