"""
This type stub file was generated by pyright.
"""

class StripCommentsFilter:
    def process(self, stmt): ...

class StripWhitespaceFilter:
    def process(self, stmt, depth=...): ...

class SpacesAroundOperatorsFilter:
    def process(self, stmt): ...

class StripTrailingSemicolonFilter:
    def process(self, stmt): ...

class SerializerUnicode:
    @staticmethod
    def process(stmt):  # -> str:
        ...
