"""
This type stub file was generated by pyright.
"""

class ReindentFilter:
    def __init__(
        self,
        width=...,
        char=...,
        wrap_after=...,
        n=...,
        comma_first=...,
        indent_after_first=...,
        indent_columns=...,
        compact=...,
    ) -> None: ...
    @property
    def leading_ws(self):  # -> int:
        ...
    def nl(self, offset=...):  # -> Token:
        ...
    def process(self, stmt): ...
