"""
This type stub file was generated by pyright.
"""

class _CaseFilter:
    ttype = ...
    def __init__(self, case=...) -> None:
        ...
    
    def process(self, stream): # -> Generator[tuple[Any, Any], Any, None]:
        ...
    


class KeywordCaseFilter(_CaseFilter):
    ttype = ...


class IdentifierCaseFilter(_CaseFilter):
    ttype = ...
    def process(self, stream): # -> Generator[tuple[Any, Any], Any, None]:
        ...
    


class TruncateStringFilter:
    def __init__(self, width, char) -> None:
        ...
    
    def process(self, stream): # -> Generator[tuple[Any, Any] | tuple[Any, LiteralString | Any], Any, None]:
        ...
    


