[project]
dependencies = [
    "cattrs>=25.1.1",
]
description = "A converter for cattrs"
name = "cattrs-converter"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[build-system]
build-backend = "uv_build"
requires = [
    "uv_build>=0.8.8,<0.9.0",
]
